// <auto-generated />
using System;
using DrSneussFactory.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DrSneussFactory.Migrations
{
    [DbContext(typeof(DrSneussFactoryContext))]
    [Migration("20200807200202_SwitchMany-2")]
    partial class SwitchMany2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DrSneussFactory.Models.Engineer", b =>
                {
                    b.Property<int>("EngineerId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("JobTitle");

                    b.Property<int>("MachineId");

                    b.Property<string>("Name");

                    b.HasKey("EngineerId");

                    b.ToTable("Engineers");
                });

            modelBuilder.Entity("DrSneussFactory.Models.EngineerMachine", b =>
                {
                    b.Property<int>("EngineerMachineId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EngineerId");

                    b.Property<int>("MachineId");

                    b.HasKey("EngineerMachineId");

                    b.HasIndex("EngineerId");

                    b.HasIndex("MachineId");

                    b.ToTable("EngineerMachine");
                });

            modelBuilder.Entity("DrSneussFactory.Models.Machine", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EngineerId");

                    b.Property<int?>("EngineerId1");

                    b.Property<string>("MachineDescription");

                    b.Property<string>("MachineName");

                    b.HasKey("MachineId");

                    b.HasIndex("EngineerId1");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("DrSneussFactory.Models.EngineerMachine", b =>
                {
                    b.HasOne("DrSneussFactory.Models.Engineer", "Engineer")
                        .WithMany("Machines")
                        .HasForeignKey("EngineerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DrSneussFactory.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DrSneussFactory.Models.Machine", b =>
                {
                    b.HasOne("DrSneussFactory.Models.Engineer", "Engineer")
                        .WithMany()
                        .HasForeignKey("EngineerId1");
                });
#pragma warning restore 612, 618
        }
    }
}
